/**
 * Author:  neiko
 * Created: Oct 26, 2016
 */

DROP TABLE Jeux IF EXISTS;
DROP TABLE Soirees IF EXISTS;
DROP TABLE Joueurs IF EXISTS;
DROP TABLE Factures IF EXISTS;
DROP TABLE Produits IF EXISTS;
DROP TABLE Ventes IF EXISTS;